name: quantGen
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - r-base
  - r-devtools=2.2
  - openjdk
  - java-jdk
  - jupyter
  - limix=3.0.3
  - python=3.7.5
  - r-rjava
  - r-lme4
  - r-plot.matrix
  - r-sommer
  - r-rtassel