Sys.setenv(TAR = "/bin/tar")
options(repos = "https://cloud.r-project.org/")
install.packages("remotes")
install.packages("BiocManager")
if (!require("devtools")) install.packages("devtools")
install.packages("rJava")
devtools::install_bitbucket(repo = "bucklerlab/rTASSEL",ref = "master",build_vignettes = FALSE)
install.packages("sommer")
install.packages("plot.matrix")
install.packages("MASS")
install.packages("lme4")
install.packages("hmisc")